openapi: 3.0.0
info:
  version: 1.0.0
  title: Foodies API
  description: 'The API for foodies project under cloud computing spring 2021, NYU'
  termsOfService: https://cc-s2021-foodies.com/terms-of-use
  contact:
    name: Prasant Adhikari
    url: prasantadh.github.io
    email: pa1038@nyu.edu
  license:
    name: Foodies License
    url: https://cc-s2021-foodies.com/license
  
paths: 
  /users/{id}:
    get:
      description: Obtain information about specific user
      parameters: 
        - in: path
          name: id
          required: true
          description: The id of the user
          schema:
            type: integer
            example: 32
      responses:
        200:
          description: Successfully found the user
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/User'
    
  /user_recipes/:
    get:
      description: Obtain Recipes belonging to a user
      parameters: 
        - in: query
          name: user_recipes
          required: true
          schema:
            type: string
            example: "sample-user"
                
      responses:
        200:
          description: Succesfully received the user recipes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllRecipes'
    
  /recipe_by_ingredients/:
    get:
      description: Obtain Recipes given ingredients
      parameters: 
        - in: query
          name: ingredients
          required: true
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Ingredient'
            example: 
              - name: "salt"
              - name: "peanuts"
      responses:
        200:
          description: Succesfully received the user recipes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllRecipes'
    
  /recipes/{id}:
    get:
      description: Obtain information about specific recipe
      parameters:
        - in: path
          name: id
          required: true
          description: The id of the recipe
          schema:
            type: string
            example: "1"
      responses:
        200:
          description: Successfully found a recipe
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Recipe'
            
components:
  schemas:
    User:
      description: Model containing user info
      properties:
        name:
          type: string
          example: prasantadh
    
    AllRecipes:
      description: A collection of Recipes
      type: array
      items: 
        $ref: '#/components/schemas/Recipe'
      example:
        - name: "Tap Water"
          recipe: "1. Get it from the tap"
        - name: "Bottled Water"
          recipe: "1. Find a convenience store"
    
    Recipe:
      description: Model containing recipe info
      properties:
        name:
          type: string
          example: "nyc tap water"
        recipe:
          type: string
          example: "1. get it from the tap"
    
    AllIngredients:
      description: A collection of ingredients
      type: array
      items:
        $ref: '#/components/schemas/AllIngredients'
    
    Ingredient:
      description: Model containing an ingredient
      properties:
        name:
          type: string
          example: "peanuts"
      
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/prasantadh/cc-s2021-foodies/1.0.0
